variables:
  RELEASE_ANDROID_PATH: 'C:\Users\45222\Git\pointz\Releases\PointZ\Android'
  MSBUILD_PATH: 'D:\Programs\Microsoft Visual Studio\2022\Preview\Msbuild\Current\Bin\MSBuild.exe'
  NUGET_PATH: 'Z:\Programmering\NuGet\nuget.exe'
  CSPROJ_ANDROID_PATH: './PointZ/PointZ/PointZ.Android/PointZ.Android.csproj'
  
stages:
  - build

# Android
android_release_apk:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - '& "$env:NUGET_PATH" restore "$env:CSPROJ_ANDROID_PATH"' # Restore NuGet Dependencies
    - '& "$env:MSBUILD_PATH" "$env:CSPROJ_ANDROID_PATH" /t:Clean /p:Configuration=Release' # Clean
    - '& "$env:MSBUILD_PATH" "$env:CSPROJ_ANDROID_PATH" /t:Build /p:Configuration=Release' # Build
    - '& "$env:MSBUILD_PATH" "$env:CSPROJ_ANDROID_PATH" /p:Configuration=Release /t:PackageForAndroid /p:OutputPath="$env:RELEASE_ANDROID_PATH"' # APK

# Saving for later: /t:SignAndroidPackage 